# Generated by Django 3.2.7 on 2021-10-20 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MAccountsReceivable',
            fields=[
                ('timestamp', models.DateField(auto_now_add=True)),
                ('snid', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(max_length=50)),
                ('valueLoaned', models.DecimalField(decimal_places=2, max_digits=10)),
                ('default', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unitsLoaned', models.IntegerField()),
                ('valuePayed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dateOpened', models.DateField(null=True)),
                ('dateClosed', models.DateField(null=True)),
                ('dueDate', models.DateField(null=True)),
                ('customerID', models.IntegerField()),
                ('recieptID', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Accounts Receivable',
                'ordering': ['snid'],
            },
        ),
    ]
