# Generated by Django 3.2.9 on 2021-12-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_maccountspayable_mallowancefordoubtfulaccounts_mbuilding_mbuildingimprovements_mcapital_mcomputerequ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mrawmaterials',
            name='inchesPerPc',
            field=models.DecimalField(decimal_places=2, default='0.00', help_text='Full length of the Item.', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='mrawmaterials',
            name='inchesPerUnit',
            field=models.DecimalField(decimal_places=2, default='0.00', help_text='Break the Tube into 1/4s.', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='mrawmaterials',
            name='pcsPerCs',
            field=models.DecimalField(decimal_places=2, default='0.00', help_text='Total Items in a Case.', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='mrmin',
            name='pcsIn',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=5),
        ),
        migrations.AlterField(
            model_name='mrmout',
            name='rnd',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=5),
        ),
        migrations.AlterField(
            model_name='mrmout',
            name='units',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=5),
        ),
        migrations.AlterField(
            model_name='mrmout',
            name='waste',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=5),
        ),
    ]
