# Generated by Django 4.0.3 on 2022-04-05 15:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_mcustomwork_qrcode_mcustomwork_squarelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='mstoreinventory',
            name='qrcode',
            field=models.ImageField(default=datetime.datetime(2022, 4, 5, 15, 56, 43, 954815, tzinfo=utc), upload_to='storeInventory/qrcodes/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mstoreinventory',
            name='squareLink',
            field=models.CharField(default=datetime.datetime(2022, 4, 5, 15, 56, 54, 997277, tzinfo=utc), max_length=500),
            preserve_default=False,
        ),
    ]
