# Generated by Django 4.0.3 on 2022-04-05 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_mstoreinventory_qrcode_mstoreinventory_squarelink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcustomwork',
            name='image',
            field=models.ImageField(upload_to='custom/img/'),
        ),
        migrations.AlterField(
            model_name='mproductionwork',
            name='image',
            field=models.ImageField(upload_to='prodo/img/'),
        ),
        migrations.AlterField(
            model_name='mprototypes',
            name='image',
            field=models.ImageField(upload_to='proto/img/'),
        ),
        migrations.AlterField(
            model_name='mstoreinventory',
            name='image',
            field=models.ImageField(upload_to='storeInventory/img/'),
        ),
    ]
