# Generated by Django 4.0.5 on 2022-06-02 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_alter_mcustomwork_image_alter_mproductionwork_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mproductionwork',
            name='image2',
            field=models.ImageField(null=True, upload_to='prodo/img/'),
        ),
        migrations.AddField(
            model_name='mproductionwork',
            name='image3',
            field=models.ImageField(null=True, upload_to='prodo/img/'),
        ),
        migrations.AddField(
            model_name='mproductionwork',
            name='image4',
            field=models.ImageField(null=True, upload_to='prodo/img/'),
        ),
        migrations.AddField(
            model_name='mproductionwork',
            name='image5',
            field=models.ImageField(null=True, upload_to='prodo/img/'),
        ),
        migrations.AlterField(
            model_name='mproductionwork',
            name='image',
            field=models.ImageField(null=True, upload_to='prodo/img/'),
        ),
        migrations.AlterField(
            model_name='mproductionwork',
            name='qrcode',
            field=models.ImageField(null=True, upload_to='prodo/qrcodes/'),
        ),
        migrations.AlterField(
            model_name='mproductionwork',
            name='squareLink',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
